server:
  port: 9000

spring:
  application:
    name: service-sse-push
  cloud:
    nacos:
      discovery:
        server-addr: "${NACOS_SERVER_ADDR:localhost:8848}"
        username: "${NACOS_USERNAME:nacos}"
        password: "${NACOS_PASSWORD:}"
