spring:
  application:
    name: service-map
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
server:
  port: 8085

amap:
  key: 8d6ad7004c8ed0c8f2fd4f2a932a87a9
