server:
  port: 8081
spring:
  application:
    name: api-passenger
  cloud:
    nacos:
      discovery:
        server-addr: "${NACOS_SERVER_ADDR:localhost:8848}"
        username: "${NACOS_USERNAME:nacos}"
        password: "${NACOS_PASSWORD:}"
  redis:
    host: "${REDIS_HOST:localhost}"
    port: "${REDIS_PORT:6379}"
    database: "${REDIS_DATABASE:0}"


logging:
  level:
    com.george.apipassenger.remote: DEBUG  # feign 客户端包路径

